<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="f"%>
<spring:url value="/" var="baseurl"></spring:url>
<spring:url value="/style/datepicks" var="datepicks" />
<spring:url value="/img" var="img_url" />
<spring:url value="/style" var="style_url" />
<spring:url value="/css" var="css_url" />
<link rel="stylesheet" type="text/css" href="${css_url}/setting.css">
<link href="${datepicks}/jquery.datepick.css" rel="stylesheet">
<script src="${datepicks}/jquery.plugin.js"></script>
<script src="${datepicks}/jquery.datepick.js"></script>

<script>
	$(function() {
		$('#noticeDate').datepick({
			dateFormat : "yyyy-mm-dd"
		});
	});
	function goBackAndRefresh() {
		document.cookie = 'auto-refresh=YES';
		history.go(-1);
	}
	$(function() {
		setTimeout(function(){
			  $('.successmsg').remove();
			}, 5000);
		document.getElementById("validate").reset();
	});
</script>
<div id="content_wrapper">
	<div id="side_bar">

		<div id="sidebar_news_area"></div>
	</div>
	<div id="content">
		<div id="content-header">
			<img alt="Show_settings" src="${img_url}/notice1.jpg"
				style="width: 74px; height: 74px;">
			<h1>Create Notice</h1>
			<h3>Create new notice</h3>
			<div id="app-back-button">
				<a href="home"><img alt="Back" border="0"
					src="${img_url}/home.png"
					style="margin-top: -6px; height: 40px; width: 40px;"></a> <a
					href="#" onclick="javascript:location.reload(true);"><img
					alt="Back" border="0" src="${img_url}/refresh.png"
					style="margin-top: -6px; height: 40px; width: 40px;"></a> <a
					href="#" onclick="history.back(); return false;"><img
					alt="Back" border="0" src="${img_url}/back.png"
					style="margin-top: -6px; height: 40px; width: 40px;"></a>
			</div>
		</div>
		<c:if test="${! empty msg}">
			<div class="successmsg">${msg}</div>
		</c:if>
		<div id="page-yield">
			<div id="box">
				<f:form id="validate" action="create-notice"
					commandName="noticetDTO" target="_blank">
					<table>
						<tr>
							<td>Subject:<font color="red">*</font></td>
							<td><input type="text" name="noticeSubject"
								id="noticeSubject" class="validate[required,minSize[2]]"
								style="margin-left: 60px;"></td>
						</tr>
						<tr>
							<td><br></td>
						</tr>
						<tr>
							<td>Date:<font color="red">*</font></td>
							<td><input type="text" size="30px" name="noticeDate"
								id="noticeDate" style="margin-left: 60px;"
								class=" validate[required]"></td>
						</tr>
						<tr>
							<td><br></td>
						</tr>
						<tr>
							<td>Generated By:<font color="red">*</font></td>
							<td><input type="text" size="30px" name="genratedBy"
								id="generatedBy" style="margin-left: 60px;"
								class=" validate[required,minSize[2]"></td>
						</tr>
						<tr>
							<td><br></td>
						</tr>
						<tr>
							<td>Description:<font color="red">*</font></td>
							<td><textarea rows="1" cols="10" name="noticeDescription"
									id="noticeDescription" style="margin-left: 60px;"
									class="validate[required,minSize[2],maxSize[200]"></textarea></td>
						</tr>
						<tr>
							<td><br> <br></td>
						</tr>
						<tr>
							<td></td>
							<td><input type="submit" value="Create Notice" class="btn"
								style="margin-left: 60px;" /> <!-- <a
								href="javascript:myfunction();" class="btn"
								style="margin-left: 60px;">Create Notice</a> --></td>
						</tr>
						<tr>
							<td></td>
							<td style="color: fuchsia;">${create}</td>

						</tr>
					</table>
				</f:form>
			</div>
		</div>
	</div>
</div>

<div class="extender" id="msg"></div>

